Add support for getting data from morph.io scrapers
everypolitician/morph_scraper-database pull request #1
Opened 2016-10-07 17:23 UTC by chrismytton

# What does this do?

This adds 3 new methods for getting data from a remote morph scraper, `MorphScraper::Database#data`, `MorphScraper::Database#table` and `MorphScraper::Database#query`. All of these methods return an array of hashes representing the records from the remote scraper's database.

```ruby
db = MorphScraper::Database.new('tmtmtmtm/malta-parliament')

# Equivalent to 'SELECT * FROM data'
db.data

# Equivalent to 'SELECT * FROM terms'
db.table(:terms)

# Or just execute arbitrary queries
db.query('SELECT *, 5 as term FROM data')
```

# Why was this needed?

This gem already [has a method](https://github.com/everypolitician/morph_scraper-database/blob/bcfd6fb77d288d2e59ca5405fea9f561f1ba6db3/lib/morph_scraper/database.rb#L14-L21) for copying the database from another morph scraper into the current scraper's `data.sqlite`, but it completely overwrites what's in the current scrapers database. This is OK if you've just created a new scraper and want the new scraper's database to be identical to the old one, but falls down for anything more complicated than that.

To solve this problem this pull request adds the methods mentioned above to give you full programatic access to the contents of a morph scraper. This can be used by a scraper to import the partial contents of another scraper. It can also potentially be used as part of the everypolitician-data build process to make it easier to work with remote scrapers.

# Implementation notes

This is built on top of [Sequel](https://github.com/jeremyevans/sequel), so most of the heavy lifting is done by that gem, with this gem just shuttling the data around and providing some convenience methods for accessing the data.

2016-10-07 17:29 UTC, chrismytton commented
@tmtmtmtm 👀

2016-10-09 07:10 UTC, tmtmtmtm requested changes
Woot! I'm not totally convinced by the naming of the `table` method though. I'm not sure what I would have expected such a method to actually be, but having it return the _contents_ of that table would probably have been quite far down that list.

I'm not totally sure what would be better though. Did you consider having `data` take an optional argument for which table to read from?

PS: You also seem to have forgotten to update the README…

2016-10-10 16:47 UTC, chrismytton commented
> I'm not totally sure what would be better though. Did you consider having data take an optional argument for which table to read from?

Ah, I hadn't considered that because in my head the method was called `#data` because it was returning rows from the `data` table. However on further consideration I think that having a general purpose `#data` method that takes an optional table name and defaults to the `data` table makes sense. I've made that change in https://github.com/everypolitician/morph_scraper-database/pull/1/commits/c90fc47e9ae8e41ae080eab1a45f9639dbb2a564.

> PS: You also seem to have forgotten to update the README…

😳  Done in dfc323b765b543c62f6956b168810d38cd550753

@tmtmtmtm 👀

2016-10-11 14:23 UTC, tmtmtmtm commented on README.md
>  **Note**: The above code will overwrite the database of the _current_ scraper with the contents of the _named_ scraper's database **every single time** this code is run. You might want to make this c
NB: not from this change, but there's a typo here: 'loose' should be 'lose'

2016-10-11 14:35 UTC, chrismytton commented
Just discussed this in Slack with @tmtmtmtm and decided that adding a dependency on `sequel` _and_ `sqlite3` is probably a bit extreme for our use case.

I think a better course of action will be to execute the queries against morph's API (#2) which is more in keeping with our use pattern, where we generally just do one query against one scraper. This also means we won't need to add any extra dependencies. Then we can come back to this pull request and see if we _actually_ want to add support for using a local SQLite database.

2016-10-17 16:05 UTC, chrismytton commented
The simpler version that use the Morph JSON API was implemented in #3, so I'm going to close this.

We might want to revisit the concept of having a local database and querying it with Sequel in the future, but it will almost certainly look different to this pull request.

2016-10-17 16:05 UTC, closed without merging